### ISSUE TITLE
/pkg/ is broken on new GAE

### ISSUE THREAD

**Issue by elithrar** [gorilla/gorilla.github.io#17]
https://www.gorillatoolkit.org/pkg/

HTTP 500's. Need to investigate.

**Comment by elithrar** [comment]
Interim fix will be to redirect to `pkg.go.dev/gorilla/<name>`

**Comment by arieroos** [comment]
I'm still getting internal server errors instead of redirects

![Screenshot 2020-09-04 at 12 44 26](https://user-images.githubusercontent.com/44861268/92231071-684ec600-eeac-11ea-995c-ef20624358e9.png)

**Comment by elithrar** [comment]
(I haven't fixed it. I have had zero time to do so)

**Comment by arieroos** [comment]
Ah, then I misunderstood your comment of Aug 27.

**Comment by max-bertinetti** [comment]
@elithrar I think something like this?
https://pkg.go.dev/mod/github.com/gorilla/context
istead of /pkg/context in the home template will do?

`<li><a href="/pkg/context">gorilla/context</a> stores global request variables.</li>`


If it's this the fix I can do it and make a PR

**Comment by elithrar** [comment]
Addressed in 16b4009.

It's likely we will lean on GitHub more going forward - the original site was not authored by anyone here, and does a lot of magic to build package indexes that are high-cost vs. the value they provide to maintain going forward.
