### ISSUE TITLE
[bug] Footer links for Icon and Font designer are out of date

### ISSUE THREAD

**Issue by arusso** [gorilla/gorilla.github.io#19]
**Describe the bug**

Footer links for Icon and Font creator no longer link to pages that work.

**Steps to Reproduce**

Click the link for Martin Bérubé and notice you get a permission denied error.

Click the link for  Vernon Adams and you are taken to a Google Plus page explaining the G+ is no longer a thing.

**Expected behavior**

Links take me to a page relevant to the artists.

A quick check shows Martin's web profiles point to https://www.how-to-draw-funny-cartoons.com/ as their homepage.

Vernon has since passed away in 2016 and the most official looking place I could find was their GitHub page at https://github.com/vernnobile

**Comment by arusso** [comment]
For Vernon Adams, http://sansoxygen.com/ appears to be their homepage kept up by their widow.

**Comment by coreydaley** [comment]
We will update this when github.com/gorilla/gorilla.github.io is published.
