### ISSUE TITLE
feeds: example syntax missing end quote

### ISSUE THREAD

**Issue by ghost** [gorilla/gorilla.github.io#9]
http://www.gorillatoolkit.org/pkg/feeds

the first part of examples has this with the missing end quote on the import
```
import (
    "time"
    . "github.com/gorilla/feeds
)
```

**Comment by elithrar** [comment]
Thanks for the report. The code is contained in `doc.go` - would you be up for submitting a pull request?

**Comment by ghost** [comment]
PR: https://github.com/gorilla/feeds/pull/49
